### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fulmok** [MightyKyloRen/GoogleMapsScrapping#1]
DevTools listening on ws://127.0.0.1:50504/devtools/browser/1aa80353-34a6-4b21-833d-a1535993cdec
[8260:16252:0205/170614.271:ERROR:device_event_log_impl.cc(215)] [17:06:14.271] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
10
20
22
32
42
52
62
72
82
92
102
112
122
122
122
122
122
122
122
122
122
122
122
122
[8260:1476:0205/170708.167:ERROR:util.cc(134)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
122
122
122
122
122
122
122
122
122
error
Traceback (most recent call last):
  File "c:\Users\user1\Documents\python\web-scrap-3.py", line 79, in <module>
    Selenium_extractor()
  File "c:\Users\user1\Documents\python\web-scrap-3.py", line 40, in Selenium_extractor
    action.scroll_from_origin(scroll_origin, 0, 100).perform()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\action_chains.py", line 73, in perform
    self.w3c_actions.perform()
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 91, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=109.0.5414.120)
Stacktrace:
Backtrace:
        (No symbol) [0x010D6643]
        (No symbol) [0x0106BE21]
        (No symbol) [0x00F6DA9D]
        (No symbol) [0x00F709E4]
        (No symbol) [0x00F708AD]
        (No symbol) [0x00F70B30]
        (No symbol) [0x00FA84C5]
        (No symbol) [0x00FA7856]
        (No symbol) [0x00FDE57F]
        (No symbol) [0x00FBFD7C]
        (No symbol) [0x00FD6B09]
        (No symbol) [0x00FBFB76]
        (No symbol) [0x00F949C1]
        (No symbol) [0x00F95E5D]
        GetHandleVerifier [0x0134A142+2497106]
        GetHandleVerifier [0x013785D3+2686691]
        GetHandleVerifier [0x0137BB9C+2700460]
        GetHandleVerifier [0x01183B10+635936]
        (No symbol) [0x01074A1F]
        (No symbol) [0x0107A418]
        (No symbol) [0x0107A505]
        (No symbol) [0x0108508B]
        BaseThreadInitThunk [0x774400F9+25]
        RtlGetAppContainerNamedObjectPath [0x77587BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77587B8E+238]

**Comment by fulmok** [comment]
link = "https://www.google.com/maps/search/farmacia+joinville/@-26.2793953,-48.8699401,15z/data=!3m1!4b1"

**Comment by ravikola02** [comment]
update line 33 as "if le > 10". If you still need help, feel free to reach out to me at tech4biz2biz@gmail.com

**Comment by ravikola02** [comment]
Did this work?
